application: srikanth-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /html
  static_dir: html
  
- url: /images
  static_dir: images

- url: /.*
  script: BlackJack.app
